project:
  type: book
  output-dir: ../docs

book:
  title: "The Experimental Music Toolbox (EMT)"
  author: "M. Edward (Ed) Borasky"
  date: "2024-05-14"
  chapters:
    - index.qmd
    - part: "Part 1: Windows Subsystem for Linux CPU Mode"
      chapters:
        - 10_Getting_Started.qmd
        - 20_Linux_Music_Packages.qmd
        - 30_RStudio_Server.qmd
        - 40_JupyterLab.qmd
        - 50_PyTorch_and_Torchaudio.qmd
        - 60_ChucK_from_Source.qmd
    - part: "Part 2: NVIDIA GPUs in CUDA Mode"
      chapters: 
        - 62_GPU-enabled_PyTorch.qmd
        - 64_CUDA_Toolkit.qmd
    - part: "Part 3: Distrobox Containers, Fedora Atomic Desktops and Universal Blue Linux systems"
      chapters:
        - 70_Pet_Containers_and_Distrobox.qmd
        - 80_Fedora_Atomic_Desktops.qmd
        - 82_Universal_Blue_Linux_Systems.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
  pdf:
    documentclass: scrreprt

editor: visual
