project:
  type: book
  output-dir: "../docs"

book:
  title: "ChucK-in-the-Box"
  subtitle: "A minimalist approach to live coding"
  author: "M. Edward (Ed) Borasky"
  date: "5/13/2025"
  chapters:
    - index.qmd
    - getting-the-hardware.qmd
    - installing-the-software.qmd
    - connecting-to-windows-11.qmd
    - connecting-to-linux.qmd
    - references.qmd

bibliography: REFERENCES.bib

format:
  html:
    theme: 
      - darkly
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

