name: JupyterLab
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - jupyter_server
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - nvitop
  - pandas
  - pip
  - pip:
    - jupyterlab-quarto
  - pytorch
  - scikit-learn
  - scipy
  - sympy
  - torchaudio
