name: JupyterLab
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - cudnn
  - cutensor
  - cupy
  - jupyter_server
  - jupyterlab
  - matplotlib
  - nccl
  - numba
  - numpy
  - nvitop
  - pandas
  - pip
  - pip:
    - jupyterlab-quarto
  - pytorch
  - pytorch-cuda
  - scikit-learn
  - scipy
  - sympy
  - torchaudio
